name: Build Java + C++ (Windows)

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"

      - name: Compile Java & generate JNI headers
        shell: pwsh
        run: |
          New-Item -ItemType Directory -Force -Path target/classes, cpp_core/include | Out-Null
          javac -h cpp_core/include -d target/classes java_cli/src/com/example/app/*.java

      - name: Build C++ DLL (MSVC)
        shell: cmd
        run: |
          set JH=%JAVA_HOME%
          cl /I"%JH%\include" /I"%JH%\include\win32" /LD cpp_core\src\core.cpp /Fe:cpp_core\libcore.dll

      - name: Package JAR + runner
        shell: pwsh
        run: |
          jar --create --file app.jar -C target/classes .
          "@echo off`r`nsetlocal`r`njava -Djava.library.path=cpp_core -cp app.jar com.example.app.Main`r`nendlocal" | Out-File -Encoding ascii run.bat

      - name: Upload artifact (Windows)
        uses: actions/upload-artifact@v4
        with:
          name: windows-build-output
          path: |
            app.jar
            run.bat
            cpp_core/libcore.dll
